# Generated by Django 5.2.7 on 2025-10-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_forumgroup_groupmessage_groupmemberstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📚', help_text='Emoji pour la catégorie', max_length=10)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de ressource',
                'verbose_name_plural': 'Catégories de ressources',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('type_ressource', models.CharField(choices=[('article', '📝 Article'), ('guide', '📖 Guide pratique'), ('video', '🎥 Vidéo'), ('audio', '🎧 Audio/Podcast'), ('infographie', '📊 Infographie'), ('exercice', '✍️ Exercice pratique')], default='article', max_length=20)),
                ('description', models.TextField(max_length=300, verbose_name='Description courte')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu complet')),
                ('lien_externe', models.URLField(blank=True, help_text='Lien vers une vidéo YouTube, article externe, etc.', null=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='ressources/')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('duree_lecture', models.IntegerField(default=5, help_text='Durée estimée en minutes')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200)),
                ('vues', models.IntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_creees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='application.categorieressource')),
                ('favoris', models.ManyToManyField(blank=True, related_name='ressources_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_modifie', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='application.ressource')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_complete', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='application.ressource')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'unique_together': {('utilisateur', 'ressource')},
            },
        ),
    ]
