# Generated by Django 5.2.7 on 2025-10-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_categorieressource_ressource_commentaireressource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('confirmee', '✅ Confirmée'), ('rejetee', '❌ Rejetée'), ('completee', '🏁 Complétée'), ('annulee', '🚫 Annulée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('reponse_psychologue', models.TextField(blank=True)),
                ('date_prochaine_session', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de consultation',
                'verbose_name_plural': 'Demandes de consultation',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='MessageConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='application.consultationrequest')),
            ],
            options={
                'verbose_name': 'Message de consultation',
                'verbose_name_plural': 'Messages de consultation',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Psychologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialites', models.CharField(help_text='Ex: Anxiété, Dépression, Stress - séparées par des virgules', max_length=200)),
                ('biographie', models.TextField(blank=True)),
                ('experience_ans', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('taux_reponse_moyen', models.FloatField(default=0.0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologue_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psychologue',
                'verbose_name_plural': 'Psychologues',
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='psychologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='application.psychologue'),
        ),
    ]
