# Generated by Django 5.2.7 on 2025-10-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_consultationrequest_messageconsultation_psychologue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text='Pour formations, ateliers et conférences', null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Optionnel', null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='fichier_audio',
            field=models.FileField(blank=True, help_text='Fichier audio MP3 pour les podcasts (optionnel si lien externe)', null=True, upload_to='podcasts/'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='intervenant',
            field=models.CharField(blank=True, help_text="Nom de l'intervenant pour conférences, formations et ateliers", max_length=200, verbose_name='Intervenant/Formateur'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='lieu',
            field=models.CharField(blank=True, help_text="Adresse physique, 'En ligne', ou lien de visioconférence", max_length=200, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='places_disponibles',
            field=models.IntegerField(blank=True, help_text='Nombre de places disponibles (laisser vide pour illimité)', null=True, verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='contenu',
            field=models.TextField(blank=True, help_text='Pour les articles, guides et supports de conférence', verbose_name='Contenu complet'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='duree_lecture',
            field=models.IntegerField(default=5, help_text='Durée estimée en minutes', verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='est_publie',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='lien_externe',
            field=models.URLField(blank=True, help_text='Lien YouTube pour vidéos, Spotify pour podcasts, Zoom pour ateliers', null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type_ressource',
            field=models.CharField(choices=[('article', '📝 Article'), ('guide', '📖 Guide pratique'), ('video', '🎥 Vidéo'), ('podcast', '🎧 Podcast'), ('formation', '🎓 Formation'), ('atelier', '🛠️ Atelier'), ('conference', '🎤 Conférence')], default='article', max_length=20, verbose_name='Type de ressource'),
        ),
    ]
