# Generated by Django 5.2.7 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_post_commentairepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='category',
            field=models.CharField(choices=[('anxiete', '💭 Anxiété'), ('depression', '💙 Dépression'), ('meditation', '🧘 Méditation'), ('famille', '👨\u200d👩\u200d👧\u200d👦 Famille'), ('developpement', '🌱 Développement personnel'), ('stress', '⚡ Stress & Burn-out'), ('trauma', '🛡️ Trauma & PTSD'), ('sommeil', '🌙 Troubles du sommeil'), ('relations', '💞 Relations & Amour'), ('deuil', '🕊️ Deuil & Perte'), ('confiance', '⭐ Confiance en soi'), ('addiction', '🔗 Addictions'), ('colere', '🔥 Gestion de la colère'), ('solitude', '🫂 Solitude & Isolement'), ('identite', '🌍 Identité & Culture'), ('jeunes', '🎓 Santé mentale des jeunes'), ('spiritualite', '✨ Spiritualité & Foi'), ('alimentation', '🥗 Alimentation & Image du corps')], max_length=50),
        ),
    ]
