# Generated by Django 5.2.7 on 2026-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_add_forum_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Vidéo'),
        ),
    ]
