# Generated by Django 5.2.7 on 2026-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_add_video_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='psychologues/', verbose_name='Photo de profil'),
        ),
    ]
