# Generated by Django 5.2.7 on 2026-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_add_photo_to_psychologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='acces',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('premium', 'Premium')], default='gratuit', max_length=10, verbose_name='Accès'),
        ),
    ]
