# Generated by Django 5.2.7 on 2026-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_ressource_acces'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='fichier_video',
            field=models.FileField(blank=True, help_text='Fichier vidéo uploadé directement (MP4, MOV…)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type_ressource',
            field=models.CharField(choices=[('article', 'Article'), ('guide', 'Guide pratique'), ('video', 'Vidéo'), ('podcast', 'Podcast'), ('formation', 'Formation'), ('atelier', 'Atelier'), ('conference', 'Conférence')], default='article', max_length=20, verbose_name='Type de ressource'),
        ),
    ]
