# Generated by Django 5.2.7 on 2026-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_customuser_bio_customuser_photo_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='type_seance',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence')], default='presentiel', max_length=15, verbose_name='Type de séance'),
        ),
    ]
