# Generated by Django 5.2.7 on 2026-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsante',
            name='poids',
            field=models.FloatField(help_text='Poids en kg'),
        ),
        migrations.AlterField(
            model_name='profilsante',
            name='taille',
            field=models.IntegerField(help_text='Taille en cm'),
        ),
    ]
