# Generated by Django 5.2.7 on 2026-03-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_profilsante_poids_alter_profilsante_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('mood_detected', models.CharField(choices=[('unknown', 'Inconnu'), ('positif', 'Positif'), ('neutre', 'Neutre'), ('anxieux', 'Anxieux'), ('triste', 'Triste'), ('crisis', 'En crise')], default='unknown', max_length=20)),
                ('crisis_flag', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de chat IA',
                'verbose_name_plural': 'Sessions de chat IA',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('crisis_flag', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='application.chatsession')),
            ],
            options={
                'verbose_name': 'Message chatbot IA',
                'verbose_name_plural': 'Messages chatbot IA',
                'ordering': ['sent_at'],
            },
        ),
    ]
