# Generated by Django 5.2.7 on 2026-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_add_chatbot_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
