# Generated by Django 6.0.5 on 2026-09-01 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_add_post_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
