# Generated by Django 6.0.5 on 2026-09-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_add_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='gratitude',
            field=models.TextField(blank=True, default='', help_text='Une ligne par élément de gratitude'),
        ),
    ]
