# Generated by Django 6.0.5 on 2026-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_journalentry_gratitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='humeur',
            field=models.CharField(choices=[('5', 'Soleil'), ('4', 'Éclaircies'), ('3', 'Nuageux'), ('2', 'Pluie'), ('1', 'Orage')], default='3', max_length=2),
        ),
    ]
