# Generated by Django 6.0.5 on 2026-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_journalentry_humeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='corps',
            field=models.TextField(blank=True, verbose_name='Corps riche (HTML nettoyé, blog/article)'),
        ),
        migrations.AddField(
            model_name='post',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('blog', 'Blog'), ('article', 'Article')], db_index=True, default='post', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Image (couverture pour un blog/article)'),
        ),
    ]
