# Generated by Django 6.0.5 on 2026-09-29 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_copy_blogs_into_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type_annonce', models.CharField(choices=[('info', 'Nouveauté'), ('atelier', 'Atelier / Événement'), ('alerte', 'Information importante'), ('psy', 'Disponibilité psychologue')], default='info', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('lien_externe', models.URLField(blank=True, null=True, verbose_name='Lien (inscription, détails...)')),
                ('est_publiee', models.BooleanField(default=True, verbose_name='Publiée')),
                ('est_epinglee', models.BooleanField(default=False, verbose_name='Épinglée en tête')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-est_epinglee', '-date_creation'],
            },
        ),
    ]
