# Generated by Django 6.0.5 on 2026-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_add_annonce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologue',
            options={'verbose_name': 'Spécialiste', 'verbose_name_plural': 'Spécialistes'},
        ),
        migrations.AddField(
            model_name='psychologue',
            name='type_specialiste',
            field=models.CharField(choices=[('psychologue', 'Psychologue'), ('psychiatre', 'Psychiatre'), ('psychotherapeute', 'Psychothérapeute'), ('medecin_sport', 'Médecin du sport'), ('kinesitherapeute', 'Kinésithérapeute'), ('osteopathe', 'Ostéopathe'), ('psychomotricien', 'Psychomotricien'), ('ergotherapeute', 'Ergothérapeute'), ('dieteticien', 'Diététicien / Nutritionniste'), ('coach_sportif', 'Coach sportif')], default='psychologue', max_length=30, verbose_name='Catégorie de spécialiste'),
        ),
    ]
